import type { Metadata } from "next";
import {   Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Inventory Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable}  antialiased`}
      >
        <ThemeProvider attribute={"class"}
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
        >
        {children}
        </ThemeProvider>
        <Toaster richColors/>
      </body>
    </html>
  );
}
